"""add new columns for user

Revision ID: 311847a4d6be
Revises: 41641f572261
Create Date: 2020-10-26 09:04:31.255132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311847a4d6be'
down_revision = '41641f572261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
