"""create user,account,condolence,member,member_info

Revision ID: aa4a9f38b89d
Revises: 
Create Date: 2020-12-27 07:52:37.208121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4a9f38b89d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_date', sa.Date(), nullable=True),
    sa.Column('matters', sa.String(length=50), nullable=True),
    sa.Column('a_type', sa.String(length=60), nullable=True),
    sa.Column('a_count', sa.Float(), nullable=True),
    sa.Column('in_out', sa.String(length=2), nullable=True),
    sa.Column('remark', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_a_date'), 'account', ['a_date'], unique=False)
    op.create_index(op.f('ix_account_a_type'), 'account', ['a_type'], unique=False)
    op.create_index(op.f('ix_account_in_out'), 'account', ['in_out'], unique=False)
    op.create_table('condolence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_date', sa.Date(), nullable=True),
    sa.Column('c_year', sa.Integer(), nullable=True),
    sa.Column('c_quarter', sa.Integer(), nullable=True),
    sa.Column('c_name', sa.String(length=10), nullable=True),
    sa.Column('c_type', sa.String(length=10), nullable=True),
    sa.Column('c_count', sa.Float(precision=20, asdecimal=2), nullable=True),
    sa.Column('remark', sa.String(length=50), nullable=True),
    sa.Column('in_account', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('date_year', sa.Integer(), nullable=True),
    sa.Column('date_half_year', sa.String(length=6), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ID_num', sa.String(length=20), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('membership_fee', sa.Float(), nullable=True),
    sa.Column('personnel_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_date_half_year'), 'member', ['date_half_year'], unique=False)
    op.create_index(op.f('ix_member_date_year'), 'member', ['date_year'], unique=False)
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=False)
    op.create_index(op.f('ix_member_personnel_type'), 'member', ['personnel_type'], unique=False)
    op.create_table('member_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ID_num', sa.String(length=20), nullable=True),
    sa.Column('date_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('nation', sa.String(length=20), nullable=True),
    sa.Column('political_status', sa.String(length=20), nullable=True),
    sa.Column('native_place', sa.String(length=60), nullable=True),
    sa.Column('education', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ID_num')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('member_info')
    op.drop_index(op.f('ix_member_personnel_type'), table_name='member')
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_index(op.f('ix_member_date_year'), table_name='member')
    op.drop_index(op.f('ix_member_date_half_year'), table_name='member')
    op.drop_table('member')
    op.drop_table('condolence')
    op.drop_index(op.f('ix_account_in_out'), table_name='account')
    op.drop_index(op.f('ix_account_a_type'), table_name='account')
    op.drop_index(op.f('ix_account_a_date'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
